export interface Artista{
  _id :string,
  redes : string[],
  comics : string[],
  tags: string[],
  artRecomendado : string[],
  comicRecomendado :string[],
  nombre : string,
  imgPerfil : string,
  descripcion: string,
  descripcionCorta: string,
  frase: string,
  liston: string,
  premio: string,
  posicion: string,
  estado: string,
  imgPortada: string,
  imgFondo: string,
  seguidores : number,
  casa: string,
  rango: string,
  createdAt :Date,
  updatedAt : Date
}
